DROP TABLE IF EXISTS bruker;
DROP TABLE IF EXISTS notat;

CREATE TABLE notat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tittel TEXT NOT NULL,
  tekst TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bruker (
  brukernavn TEXT PRIMARY KEY NOT NULL,
  passord TEXT NOT NULL
);